spring:
  application:
    name: saleUserBe
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.142.78.32:3306/bank?serverTimezone=Asia/Seoul
    username: root
    password: chanhanhome

  jpa:
    hibernate:
      # create, create-drop 등 사용시 db가 초기화 될 수 있으므로 조심해야함
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# file path
file:
  path: /Users/ichanhan/Desktop/uploads/

# master key
gugu:
  master-key: key
  mail-id: example
  mail-pw: example