spring:
  application:
    name: saleUserBe
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/bank?serverTimezone=Asia/Seoul
        read-only: false
        username: root
        password: password
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/bank?serverTimezone=Asia/Seoul
        read-only: true
        username: root
        password: password

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# file path
file:
  path: /Users/ichanhan/Desktop/uploads/

# master key
gugu:
  master-key: key
  mail-id: example
  mail-pw: example