server:
  ssl:
    enabled: true
    key-store: file:/cert/keystore.p12
    key-store-type: PKCS12
    key-store-password: ohuniversechan
spring:
  application:
    name: gugubank
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.142.78.32:3306/bank?serverTimezone=Asia/Seoul
    username: root
    password: chanhanhome

  jpa:
    hibernate:
      # create, create-drop 등 사용시 db가 초기화 될 수 있으므로 조심해야함
      ddl-auto: none

  data:
    redis:
      host: 172.17.0.5
      port: 6379
      database: 1

# file path
file:
  path: /bank-image/

# master key
gugu:
  master-key: 'gugumasterkey!'
  mail-id: 'ohohuniverse9@gmail.com'
  mail-pw: 'agxkwgiqzprljlzo'
